---
title: "First Knit"
author: "Rebecca Castro"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Lancaster High School and Eastside High School and yes I graduated from Eastside High. Math was always easiest for me than English. I did best in Math and Science.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I prefer to use windows as my computer. I never had a Mac book before.I would rate myself in between 5-6. My internet access is strong at my house. I use the highest speed internet with all the devices we use.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I pefer to be called Rebecca by my classmates and instructors. I don't mind be called Becca as well.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  My achievement I want in life is to stop surviving and start living. I want to no live paycheck to paycheck and have a savings. I would think Drama and Science would be the greatest interest I have. I am getting my degree in Kinesiology.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I would want to go to Greece in the future. If i had to choose a branch it would be the Air Force. I did Rotc with the Air Force and liked the chance to fly a plane or control a plane.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I am taking Math 115 and no I didn't know that Math 116 had more transferable units. I plan for a passing grade hopefully a B but will to my best. I plan to focus and get the homework done as well as attended class.
 






  




